/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekbesar.view;

import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author hp
 */
public class Gaji extends javax.swing.JFrame {
public final com.mysql.jdbc.Connection conn = (com.mysql.jdbc.Connection) koneksi.getKoneksi();

JasperReport Report;
JasperPrint Print;
Map param = new HashMap();
JasperDesign JasDes;

    public Gaji() {
        initComponents();
        
        Date date = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        txTanggal.setText(s.format(date));
    }
    
    private void simpan(){
        try {
            java.sql.Connection c = koneksi.getKoneksi();
            String sql = "INSERT INTO gaji_karyawan VALUES ('"+txId_Karyawan.getText()+"','"+txNama.getText()+"',"
                    + "'"+txPosisi.getText()+"','"+txMasa.getText()+"','"+txGaji_pokok.getText()+"','"+txLembur.getText()+"',"
                    + "'"+txAsuransi.getText()+"','"+txBonus.getText()+"','"+txGaji_bersih.getText()+"','"+txTanggal.getText()+"')";
            java.sql.PreparedStatement pst=c.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void clear(){
        txId_Karyawan.setText("");
        txNama.setText("");
        txPosisi.setText("");
        txMasa.setText("");
        txGaji_pokok.setText("");
        txLembur.setText("");
        txAsuransi.setText("");
        txBonus.setText("");
        txTanggal.setText("");
        txGaji_bersih.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txGaji_pokok = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txId_Karyawan = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txNama = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txPosisi = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txMasa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txGaji_bersih = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txLembur = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txAsuransi = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txBonus = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txTanggal = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(118, 86, 56));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("E M P L O Y E  S A L A R Y");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("G a j i  B e r s i h");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        txGaji_pokok.setEditable(false);
        jPanel1.add(txGaji_pokok, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 180, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("I D  K a r y a w a n");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));
        jPanel1.add(txId_Karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 180, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("P  E  R  H  I  T  U  N  G  A  N");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 190, -1));
        jPanel1.add(txNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 180, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("P o s i s i");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        txPosisi.setEditable(false);
        jPanel1.add(txPosisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 180, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("M a s a  K e r j a");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));
        jPanel1.add(txMasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 130, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("B o n u s");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("N a m a  L e n g k a p");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));
        jPanel1.add(txGaji_bersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 180, 70));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("B u l a n");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, -1, -1));
        jPanel1.add(txLembur, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 140, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("A s u r a n s i");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));
        jPanel1.add(txAsuransi, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 170, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("G a j i  P o k o k");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, -1, -1));
        jPanel1.add(txBonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 170, 30));

        btnHitung.setText("H  I T U N G");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        jPanel1.add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 390, -1, -1));

        btnCari.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        btnCari.setText("c a r i");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel1.add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 60, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("J u m l a h  L e m b u r");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("J a m");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));

        btnSave.setText("S A V E");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 100, -1));

        txTanggal.setEnabled(false);
        txTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTanggalActionPerformed(evt);
            }
        });
        jPanel1.add(txTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, -1));

        btnKembali.setText("K E M B A L I");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        txId_Karyawan.getText();
        
        try{
            Connection c = koneksi.getKoneksi();
                String query = "SELECT*FROM data_karyawan where id_karyawan='"+txId_Karyawan.getText()+"'";
                Statement st = c.createStatement();
                ResultSet rs = st.executeQuery(query);

                while(rs.next()){
                    txNama.setText(rs.getString("Nama"));
                    txPosisi.setText(rs.getString("Jabatan"));
                    txGaji_pokok.setText(rs.getString("Gaji_pokok"));
        }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        int Gaji_pokok = Integer.valueOf(txGaji_pokok.getText());
        int Lembur = Integer.valueOf(txLembur.getText());
        int Bonus = Integer.valueOf(txBonus.getText());
        int Asuransi = Integer.valueOf(txAsuransi.getText());
        Lembur = Lembur*10000;
        
        int Gaji_bersih;
        Gaji_bersih = (Gaji_pokok+Lembur+Bonus)-Asuransi;
        txGaji_bersih.setText(String.valueOf(Gaji_bersih));
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        simpan();
        clear();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTanggalActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gaji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txAsuransi;
    private javax.swing.JTextField txBonus;
    private javax.swing.JTextField txGaji_bersih;
    private javax.swing.JTextField txGaji_pokok;
    private javax.swing.JTextField txId_Karyawan;
    private javax.swing.JTextField txLembur;
    private javax.swing.JTextField txMasa;
    private javax.swing.JTextField txNama;
    private javax.swing.JTextField txPosisi;
    private javax.swing.JTextField txTanggal;
    // End of variables declaration//GEN-END:variables
}
