/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekbesar.view;

import com.mysql.jdbc.Connection;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import projekbesar.view.koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

import java.util.Date;
import java.sql.*;

public class Laporan extends javax.swing.JFrame {

    public final Connection conn = (Connection) koneksi.getKoneksi();
    JasperReport Report;
    JasperPrint Print;
    Map param = new HashMap();
    JasperDesign JasDes;
    
    public Laporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dawal = new com.toedter.calendar.JDateChooser();
        dakhir = new com.toedter.calendar.JDateChooser();
        btnCetakStok = new javax.swing.JButton();
        btnBarangMasuk = new javax.swing.JButton();
        btnBarangKeluar = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnGaji = new javax.swing.JButton();
        btnNeraca = new javax.swing.JButton();
        btnDataBarang = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        btnPendapatan1 = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("K A R Y A W A N");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(118, 86, 56));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekbesar/icon/sunflower (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, 0, 560, 570));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("P E L A P O R A N");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("T a n g g a l   A k h i r");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 120, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("T a n g g a l   A w a l");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 120, 20));
        jPanel1.add(dawal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 140, 30));
        jPanel1.add(dakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 140, 30));

        btnCetakStok.setText("Stok Barang");
        btnCetakStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakStokActionPerformed(evt);
            }
        });
        jPanel1.add(btnCetakStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 140, 40));

        btnBarangMasuk.setText("Barang Masuk");
        btnBarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangMasukActionPerformed(evt);
            }
        });
        jPanel1.add(btnBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 140, 40));

        btnBarangKeluar.setText("Barang Keluar");
        btnBarangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBarangKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 140, 40));

        btnTransaksi.setText("Transaksi Penjualan");
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        jPanel1.add(btnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 140, 40));

        btnGaji.setText("Gaji Karyawan");
        btnGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGajiActionPerformed(evt);
            }
        });
        jPanel1.add(btnGaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 140, 40));

        btnNeraca.setText("Neraca");
        btnNeraca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNeracaActionPerformed(evt);
            }
        });
        jPanel1.add(btnNeraca, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 140, 40));

        btnDataBarang.setText("Data Barang");
        btnDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataBarangActionPerformed(evt);
            }
        });
        jPanel1.add(btnDataBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 140, 40));

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 140, 40));

        btnPendapatan1.setText("Data Karyawan");
        btnPendapatan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendapatan1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPendapatan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCetakStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakStokActionPerformed
        // TODO add your handling code here:
        try {
            File file = new File("src/projekbesar/laporan/laporan_stok.jrxml");
            JasDes = JRXmlLoader.load(file);
            Report = JasperCompileManager.compileReport(JasDes);
            Print = JasperFillManager.fillReport(Report, param, conn);
            JasperViewer viewer = new JasperViewer(Print, false);
            viewer.setExtendedState(viewer.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
            viewer.setVisible(true);
            viewer.toFront();
        } catch (JRException e){
            JOptionPane.showMessageDialog(null, "Gagal koneksi laporan" +e);
        }
    }//GEN-LAST:event_btnCetakStokActionPerformed

    private void btnBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangMasukActionPerformed
        // TODO add your handling code here:
        try {
            param.put("awal", dawal.getDate());
            param.put("akhir", dakhir.getDate());
            File file = new File("src/projekbesar/laporan/laporan_bmasuk.jrxml");
            JasDes = JRXmlLoader.load(file);
            Report = JasperCompileManager.compileReport(JasDes);
            Print = JasperFillManager.fillReport(Report, param, conn);
            JasperViewer viewer = new JasperViewer(Print, false);
            viewer.setExtendedState(viewer.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
            viewer.setVisible(true);
            viewer.toFront();
        } catch (JRException e){
            JOptionPane.showMessageDialog(null, "Gagal koneksi laporan" +e);
        }
    }//GEN-LAST:event_btnBarangMasukActionPerformed

    private void btnBarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangKeluarActionPerformed
        // TODO add your handling code here:
        try {
            param.put("awal", dawal.getDate());
            param.put("akhir", dakhir.getDate());
            File file = new File("src/projekbesar/laporan/laporan_bkeluar.jrxml");
            JasDes = JRXmlLoader.load(file);
            Report = JasperCompileManager.compileReport(JasDes);
            Print = JasperFillManager.fillReport(Report, param, conn);
            JasperViewer viewer = new JasperViewer(Print, false);
            viewer.setExtendedState(viewer.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
            viewer.setVisible(true);
            viewer.toFront();
        } catch (JRException e){
            JOptionPane.showMessageDialog(null, "Gagal koneksi laporan" +e);
        }
    }//GEN-LAST:event_btnBarangKeluarActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        // TODO add your handling code here:
        try {
            param.put("awal", dawal.getDate());
            param.put("akhir", dakhir.getDate());
            File file = new File("src/projekbesar/laporan/laporan_penjualan.jrxml");
            JasDes = JRXmlLoader.load(file);
            Report = JasperCompileManager.compileReport(JasDes);
            Print = JasperFillManager.fillReport(Report, param, conn);
            JasperViewer viewer = new JasperViewer(Print, false);
            viewer.setExtendedState(viewer.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
            viewer.setVisible(true);
            viewer.toFront();
        }
        catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Gagal koneksi laporan" +e);
        }
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGajiActionPerformed
        // TODO add your handling code here:
        try {
            param.put("awal", dawal.getDate());
            param.put("akhir", dakhir.getDate());
            File file = new File("src/projekbesar/laporan/laporan_gaji.jrxml");
            JasDes = JRXmlLoader.load(file);
            Report = JasperCompileManager.compileReport(JasDes);
            Print = JasperFillManager.fillReport(Report, param, conn);
            JasperViewer viewer = new JasperViewer(Print, false);
            viewer.setExtendedState(viewer.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
            viewer.setVisible(true);
            viewer.toFront();
        }
        catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Gagal koneksi laporan" +e);
        }
    }//GEN-LAST:event_btnGajiActionPerformed

    private void btnNeracaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNeracaActionPerformed
        // TODO add your handling code here:
        try {
            param.put("awal", dawal.getDate());
            param.put("akhir", dakhir.getDate());
            File file = new File("src/projekbesar/laporan/laporan_neraca.jrxml");
            JasDes = JRXmlLoader.load(file);
            Report = JasperCompileManager.compileReport(JasDes);
            Print = JasperFillManager.fillReport(Report, param, conn);
            JasperViewer viewer = new JasperViewer(Print, false);
            viewer.setExtendedState(viewer.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
            viewer.setVisible(true);
            viewer.toFront();
        }
        catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Gagal koneksi laporan" +e);
        }
    }//GEN-LAST:event_btnNeracaActionPerformed

    private void btnDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataBarangActionPerformed
        // TODO add your handling code here:
        try {
            //            param.put("awal", dawal.getDate());
            //            param.put("akhir", dakhir.getDate());
            File file = new File("src/projekbesar/laporan/data_barang.jrxml");
            JasDes = JRXmlLoader.load(file);
            Report = JasperCompileManager.compileReport(JasDes);
            Print = JasperFillManager.fillReport(Report, param, conn);
            JasperViewer viewer = new JasperViewer(Print, false);
            viewer.setExtendedState(viewer.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
            viewer.setVisible(true);
            viewer.toFront();
        }
        catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Gagal koneksi laporan" +e);
        }
    }//GEN-LAST:event_btnDataBarangActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnPendapatan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendapatan1ActionPerformed
        // TODO add your handling code here:
        try {
            //            param.put("awal", dawal.getDate());
            //            param.put("akhir", dakhir.getDate());
            File file = new File("src/projekbesar/laporan/data_karyawan.jrxml");
            JasDes = JRXmlLoader.load(file);
            Report = JasperCompileManager.compileReport(JasDes);
            Print = JasperFillManager.fillReport(Report, param, conn);
            JasperViewer viewer = new JasperViewer(Print, false);
            viewer.setExtendedState(viewer.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
            viewer.setVisible(true);
            viewer.toFront();
        }
        catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Gagal koneksi laporan" +e);
        }
    }//GEN-LAST:event_btnPendapatan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarangKeluar;
    private javax.swing.JButton btnBarangMasuk;
    private javax.swing.JButton btnCetakStok;
    private javax.swing.JButton btnDataBarang;
    private javax.swing.JButton btnGaji;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnNeraca;
    private javax.swing.JButton btnPendapatan1;
    private javax.swing.JButton btnTransaksi;
    private com.toedter.calendar.JDateChooser dakhir;
    private com.toedter.calendar.JDateChooser dawal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
