/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekbesar.view;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import projekbesar.view.koneksi;


/**
 *
 * @author hp
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnKaryawan = new javax.swing.JButton();
        btnKasir = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnStok = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        btnGaji = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(118, 86, 56));
        jPanel1.setPreferredSize(new java.awt.Dimension(1126, 75));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekbesar/icon/sunflower (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekbesar/icon/sunflower (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Palace Script MT", 0, 75)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(239, 157, 8));
        jLabel3.setText("Sunflower");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("book store");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        btnKaryawan.setText("K  A  R  Y  A  W  A  N");
        btnKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaryawanActionPerformed(evt);
            }
        });
        jPanel1.add(btnKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 140, 40));

        btnKasir.setText("K  A  S  I  R");
        btnKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKasirActionPerformed(evt);
            }
        });
        jPanel1.add(btnKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 140, 40));

        btnLaporan.setText("L  A  P  O  R  A  N");
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });
        jPanel1.add(btnLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 150, 40));

        btnStok.setText("S  T  O  K");
        btnStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStokActionPerformed(evt);
            }
        });
        jPanel1.add(btnStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 140, 40));

        logout.setText("L O G  O U T");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, -1, -1));

        btnGaji.setText("P E N G G A J I A N");
        btnGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGajiActionPerformed(evt);
            }
        });
        jPanel1.add(btnGaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 150, 40));

        jButton1.setText("B U A T  A K U N");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaryawanActionPerformed
        // TODO add your handling code here:
        try{
            Connection c = koneksi.getKoneksi();
            Statement stat = c.createStatement();
            String sql = "SELECT * FROM log ORDER BY id DESC LIMIT 1";
            
            ResultSet rs = stat.executeQuery(sql);
            while(rs.next()){
                String level = (rs.getString("level"));
                if(level.equals("owner")||level.equals("HRD")){
                    new DaftarKaryawan().setVisible(true);
                    dispose();   
                }else{
                    JOptionPane.showMessageDialog(this, "Not Your Place, Dude!");
                }
        }
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnKaryawanActionPerformed

    private void btnStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStokActionPerformed
        // TODO add your handling code here:
        try{
            Connection c = koneksi.getKoneksi();
            Statement stat = c.createStatement();
            String sql = "SELECT * FROM `log` ORDER BY id DESC LIMIT 1";
            
            ResultSet rs = stat.executeQuery(sql);
            while(rs.next()){
                String level = (rs.getString("level"));
                if(level.equals("kasir")||level.equals("karyawan_gudang")||level.equals("owner")){
                    new StokBarang().setVisible(true);
                    dispose();   
                }else{
                    JOptionPane.showMessageDialog(this, "Not Your Place, Dude!");
                }
        }
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnStokActionPerformed

    private void btnKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKasirActionPerformed
        // TODO add your handling code here:
        try{
            Connection c = koneksi.getKoneksi();
            Statement stat = c.createStatement();
            String sql = "SELECT * FROM `log` ORDER BY id DESC LIMIT 1";
            
            ResultSet rs = stat.executeQuery(sql);
            while(rs.next()){
                String level = (rs.getString("level"));
                if(level.equals("kasir")||level.equals("owner")){
                    new Kasir().setVisible(true);
                    dispose();   
                }else{
                    JOptionPane.showMessageDialog(this, "Not Your Place, Dude!");
                }
        }
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnKasirActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
        try{
            Connection c = koneksi.getKoneksi();
            Statement stat = c.createStatement();
            String sql = "SELECT * FROM `log` ORDER BY id DESC LIMIT 1";
            
            ResultSet rs = stat.executeQuery(sql);
            while(rs.next()){
                String level = (rs.getString("level"));
                if(level.equals("owner")||level.equals("HRD")){
                    new Laporan().setVisible(true);
                    dispose();   
                }else{
                    JOptionPane.showMessageDialog(this, "Not Your Place, Dude!");
                }
        }
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btnLaporanActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda yakin akan keluar ?","PERINGATAN",dialogBtn);
        
        if(dialogResult==0){
            System.exit(0);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void btnGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGajiActionPerformed
        // TODO add your handling code here:
        try{
            Connection c = koneksi.getKoneksi();
            Statement stat = c.createStatement();
            String sql = "SELECT * FROM `log` ORDER BY id DESC LIMIT 1";
            
            ResultSet rs = stat.executeQuery(sql);
            while(rs.next()){
                String level = (rs.getString("level"));
                if(level.equals("owner")||level.equals("HRD")){
                    new Gaji().setVisible(true);
                    dispose();   
                }else{
                    JOptionPane.showMessageDialog(this, "Not Your Place, Dude!");
                }
        }
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnGajiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new BuatAkun().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGaji;
    private javax.swing.JButton btnKaryawan;
    private javax.swing.JButton btnKasir;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnStok;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
